---
defaultGroups:
  - sudo
  - live
  - network
  - plugdev
  - video
  - audio
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true
allowWeakPasswords: true
allowWeakPasswordsDefault: true
userShell: /bin/bash
hostname: hyggshi-os
